#!/bin/sh
path=/home/www/projects/sky/skybook

echo "Updating git"
git pull

python $path/manage.py migrate

echo "Restarting fcgi "

#kill -KILL `cat $path/pid`
#python $path/manage.py runfcgi maxspare=0 errlog=/var/log/projects/dropdb/fcgi-error.log  method=prefork host=127.0.0.1 port=3036 pidfile=$path/pid

sudo sv restart skybook

echo " ok"