#!/bin/sh

echo $(date) restarted >> /var/log/projects/skybook/restart.log
exec chpst -u www python /home/www/projects/skybook/manage.py runfcgi maxspare=1 errlog=/var/log/projects/skybook/fcgi-error.log method=prefork host=127.0.0.1 port=3036 pidfile=/home/www/projects/skybook/pid daemonize=false
